### ISSUE TITLE
Checking Prerequisites needs very long on Safari Mac

### ISSUE THREAD

**Issue by vonwenckstern** [EmbeddedMontiArc/onlineIDE#11]
- "Checking Prerequisites" does not finish on Safari Mac in normal mode (I closed the tab after 5 min)
- it finishes in private mode (do not know why)

- we should build end-to-end test for Jenkins running on different OS (but installing Mac OS X may get tricky)
- since end to end testing for all browsers will be too expensive, we should add a light-weight fall back strategy (since it happened to me twice, see comment 1 in #5, that it did not work for the checking process):
  - if the checking process returns no result within 3 Seconds, the checking process should be stopped and a window telling that the final process stopped should appear
    - in this way the checking process will not block everything else
    - but we should still figure out why it does not work on Safari?

**Comment by vonwenckstern** [comment]
what does "Checking Prerequisites" all do?

**Comment by 0xJMR** [comment]
> what does "Checking Prerequisites" all do?

The check can be sub-divided into three parts: Pre-Browser, Prerequisites and Post-Browser.
Pre-Browser handles mobile devices. Prerequisites handles LocalStorage, IndexedDB and WebAssembly. Post-Browser handles the warning message for Google Chrome. LocalStorage is tested by simply adding and removing a value. IndexedDB is tested by opening a database, adding a value to the database, getting the value from the database and deleting the value from the database. The WebAssembly test also tests for Microsoft Edge.

In my humble opinion, the problem lies with IndexedDB. What you can try is clearing your cache (with IndexedDB and LocalStorage). If that does not change anything, I would recommend on giving up on covering corner cases like Kusmenko's, because as you can see, it introduces more problems than it solves.
