### ISSUE TITLE
Allow updating page content of static.html asynchronously

### ISSUE THREAD

**Issue by vonwenckstern** [EmbeddedMontiArc/onlineIDE#15]
When opening the page:
http://ide.embeddedmontiarc.com/static.html?method=rawurlrewrite&mountPoint=EmbeddedMontiArc/Demos/bumperbot&path=/.c9/svg/bumperbot.bumperBot.html&radix=/.c9/svg/

and then clicking into sensors to load the subcomponents a flicker occurs (which is the grey website with loading logo), because the links are synchronous.
It would be nice if the JavaScript-API would support asynchronous page loading so that no flickering distracts the user. 

Maybe you set a new flag at the end `&async=true` in this case you do the following:
* wrap the content of the file in an iframe with an id like `static-file-iframe`
* add an additional JavaScript method to the load urls asynchronously like `loadAsync(url)`
* change all urls to use the JavaScript `loadAsync` function to get the data
* the implementation of `loadAsync` gets asynchronously the data (while getting the data an inconspicuous loading logo as it is done when loading the webassembly module in the IDE can be shown in the top part above the iframe) and updates the iframe (with the id `static-file-iframe`) content with the new received data

**Comment by vonwenckstern** [comment]
see
https://drive.google.com/file/d/105lqg31ZZFP653BPi5LN6ZdfK1z1ceeM/view?usp=sharing
for flicker effect

**Comment by 0xJMR** [comment]
This is all nice and good but as far as I can tell this will not drastically change the current state. Allow me to explain.

Since you are Schrick's supervisor, you probably know that two kinds of files are generated by his SVG generator: HTML and SVG. The content of the HTML files is pretty modest. There are the normal tags that one would expect in any HTML file and a table which is partially used for styling, partially to inhabit an anchor to the HTML of the main component. There is, however, also a more interesting tag in use, namely `object`. While loading is concerned, `object` behaves very similar to `iframe` as it also renders a DOM tree.

Now, let us assume that the above idea has been successfully implemented and that the content of the HTML file has been retrieved from the VFS. Then, the next step would be to update the content of the iframe. Doing so, triggers an update to the DOM tree of the iframe which leads to the "execution" of the `object` tag which consequentially leads to the rendering of the DOM tree of `object`. From a user's perspective this would mean that she still witnesses at least the second rendering of the DOM tree. This implies that as long as you cannot skip the rendering of the DOM tree, there will always be this sensation of loading.

There are a few workarounds, but it would introduce quite the coordination overhead so I am not sure whether it is really worth it.

Furthermore, I do not see the reason why you would open this issue in this repository, as this is a drawback of the current implementation of the visualization. The only thing I can offer you is to make the loading less distracting.

**Comment by vonwenckstern** [comment]
Thanks that is enough for the first. The asynchronously loading should do Manuel when generating the SVG files.

**Comment by 0xJMR** [comment]
I think this ticket is no longer an issue of the Online IDE. I will close it for now.
