### ISSUE TITLE
Provide JavaScript-API to automatically download zip file and open corresponding file in Online IDE

### ISSUE THREAD

**Issue by vonwenckstern** [EmbeddedMontiArc/onlineIDE#17]
I packed all currently available models in a zip-file:
`https://github.com/EmbeddedMontiArc/reporting/raw/master/models1a6a7c6e450b6d996a79c701efdd4e69.zip`

Now in https://embeddedmontiarc.github.io/reporting/report/reportEWT.html, I would like to add a column (2nd column) so that the user can watch the file in the nice online IDE.

For that I would e.g. love to write:
`http://ide.embeddedmontiarc.com/load.html?projectURL=https://github.com/EmbeddedMontiArc/reporting/raw/master/models1a6a7c6e450b6d996a79c701efdd4e69.zip&path=EMAM2Cpp/src/test/resources/simulator/MainController.emam`

And then the following should happen:
1. Check whether the project folder `models1a6a7c6e450b6d996a79c701efdd4e69` already exists
    * if the folder already exists, then continue with 3.
2. Download the zip file and extract it into the project folder `models1a6a7c6e450b6d996a79c701efdd4e69`
3. start the online IDE and open the the file  `EMAM2Cpp/src/test/resources/simulator/MainController.emam` of the `models...` project

the zip file ends with its content hash (since it will be build later every night), and the hash is necessary to download the zip file only once if the user wants to open multiple files from the table, but also to distinguish between different nightly builds (if the content did not change, the user also does not need to download a new zip file)

**Comment by 0xJMR** [comment]
A few notes apart from the documentation. You need to use `https://raw.githubusercontent.com/username/reponame/branchname/filename` as URL, otherwise you will run into problems with CORS headers. Furthermore, with respect to the documentation, I would recommend a `mountPoint` of `EmbeddedMontiArc/reporting/models{sha}` or alternatively `EmbeddedMontiArc/reporting/{sha}` where `{sha}` is the SHA value of the archive.

**Comment by vonwenckstern** [comment]
> A few notes apart from the documentation. You need to use https://raw.githubusercontent.com/username/reponame/branchname/filename as URL, otherwise you will run into problems with CORS headers.
Yes, there you are right.

> Furthermore, with respect to the documentation, I would recommend a mountPoint of EmbeddedMontiArc/reporting/models{sha} or alternatively EmbeddedMontiArc/reporting/{sha} where {sha} is the SHA value of the archive.
but isn't this too specific for our one use-case only?
Maybe we also have a demo site where we want to automatically load models into the IDE.
Where first is a nice text with picutures and videos what the model does and then you can directly open it in the Online-IDE.

But maybe I understood you wrong in the 2nd point.

**Comment by 0xJMR** [comment]
> Maybe we also have a demo site where we want to automatically load models into the IDE.

I suppose this page is then also hosted on GitHub pages? If so, then it has a unique `username/reponame/{sha}`, `username/reponame/zipname` or similar.

The important factor for the `mountPoint` is **uniqueness**. As long as you can guaranty uniqueness, you can put anything of the form EmbeddedMontiArc/y/z as `mountPoint`.

I hope it is clearer now, otherwise I will give a more extensive answer.

**Comment by 0xJMR** [comment]
After some reflection, I realized that you could even introduce your own namespace by starting the `username/reponame/branchname` chain with a username which is not allowed to be used by GitHub's naming policy, like `EmbeddedMontiArc:` since colons are not allowed. Then, you could pretty much do whatever you want with `reponame` and `branchname` since it is guaranteed to be collision free (unless they change that policy one day).

**Comment by 0xJMR** [comment]
I think the feature request is more or less satisfied. I am closing this ticket.
