### ISSUE TITLE
Add a small notification window at the button of cloud 9 when first initializing the parser

### ISSUE THREAD

**Issue by vonwenckstern** [EmbeddedMontiArc/onlineIDE#4]
When opening a demo project, first you do not see any outline because the first time the parse process is executed the browser translates the webassembly code to native code and this takes time.

Therefore, when executing the EMA-parser or later the EMAM-parser the first time, there should be a small window in the browser tellling that the parser will be installed (only once), and when the parsing process is done the window should be hidden.

This way the user knows that the program did not crash.

What optimization level do you use to compile the C++ code to webassembly? (hopefully the most aggressive one, so that the webassembly code becomes as fast as possible)

**Comment by 0xJMR** [comment]
Of course the most aggressive one. That's also the reason why the code has been split into four parts, ANTLR4, EmbeddedMontiArc Generated Sources, EmbeddedMontiArcMath Generated Sources and the Main Sources, since it would take an eternity to compile them all at once with the most aggressive optimization active.

However, currently there is an assertions option active which helps to debug the code. Deactivating it, might **slightly** increase the load time.

Furthermore, since I already predicted that you would bring up this issue, I actually worked on a way to cache the compiled WebAssembly module in order to circumvent a repeated translation process. However, the simple solution, which has also been proposed by the people of MDN, does not work in the Chrome browser due to restrictions in the IndexedDB which will probably be removed once WebAssembly is no longer experimental.

I think the idea of a notification might fill this void until the time arrives where WebAssembly has its own caching strategies. I will implement it in one of the next development cycles.

**Comment by vonwenckstern** [comment]
* I thought that webassembly is not experimental anymore (that's why it is enabled by default)
* does the caching work (https://developer.mozilla.org/en-US/docs/WebAssembly/Caching_modules) for Firefox? (we can say that FF has much better performance than)

**Comment by vonwenckstern** [comment]
It is a good idea to cache everything in service workers (https://developer.mozilla.org/de/docs/Web/API/Service_Worker_API/Using_Service_Workers#Browser_compatibility) so that the little small files must not be downloaded again, and if it is cached in Service Workers FF and Chrome do not parse and recompile JavaScript again.

> Chrome 42 introduced code caching — a way to store a local copy of compiled code so that when users returned to the page, steps like script fetching, parsing and compilation could all be skipped. At the time we noted that this change allowed Chrome to avoid about 40% of compilation time on future visits
> For scripts stored in Cache Storage via Service Worker: Code caching triggers for scripts in the first execution.
https://medium.com/reloading/javascript-start-up-performance-69200f43b201

**Comment by 0xJMR** [comment]
Since you do not seem to trust my judgements, here follows a long and time-consuming explanation as to why it does not work.

The gist of our approaches are similar, so I will take your code snippet as a reference for this explanation. The problem lies in the third resolve of the promise. `mod` or rather `Module` is an object which represents the compiled WebAssembly module. The preparation as it is now, has a duration of roughly seven seconds, as can be seen in Figure 1.


![time initial](https://user-images.githubusercontent.com/25683724/32492170-aeb887f0-c3b9-11e7-82da-a09625c2c247.PNG)
Figure 1. Initial Load Time.


In order to shorten the preparation time, one would want to cache this particular object. In Firefox, caching this object works without a problem. In Chrome, however, we encounter an error which can be seen in Figure 2.


![error](https://user-images.githubusercontent.com/25683724/32492493-c042a8f6-c3ba-11e7-8958-3d08d5849cf0.PNG)
Figure 2. Error encountered during caching process of the compile WebAssembly module.


The meaning of this error is that structurally cloning `Module` is not supported by Chrome and this is where the experimental aspect of my previous statements comes into play. If one opens the URL where Chrome keeps its flags (chrome://flags) and where one can enable and disable functionality at whim, one can see that there is an interesting option which stands in correlation with the above error and which can be seen in Figure 3. This option's `default` value is `disabled`.


![option](https://user-images.githubusercontent.com/25683724/32492872-05c855a0-c3bc-11e7-907d-369a8dea1f92.PNG)
Figure 3. Option which has to be enabled in order to allow compiled WebAssembly modules to be cached.


Enabling this flag and running the same code again yields a preparation time of rounded two seconds as can be seen in Figure 4.


![time later](https://user-images.githubusercontent.com/25683724/32493028-a691c3ae-c3bc-11e7-888c-9400c7b708f1.PNG)
Figure 4. Preparation time after caching the compile WebAssembly module.

I think I do not have to explain the implications of this.

**Comment by vonwenckstern** [comment]
I believe you. I just figured out in the post above that you can also cache JavaScript and HTMl in Chrome, so that actually nearly no request (and esp. no JavaScirpt parsing and compiling) is needed.

But the speed is right now pretty fast.
Maybe you can add at the beginning of the website an information windows (at the bottom and closeable) where you say that you should enable WebAssembly structured cloning plus a link to get directly there `chrome://settings/<webassembly>`.
Then we can clone it if it is enabled and otherwise we cannot (but then we warned the user).

It is very interesting to see that we are with caching about 4.5x faster ;)

**Comment by vonwenckstern** [comment]
The new loading reference at the top right part is nice.
And opening the main default file is also very nice.
But when the webassembly module has been loaded, the outline of the already opened file is not shown; I needed to add a new file and then tab back to get the outline.
(Tested it with Safari on Macbook)

**Comment by 0xJMR** [comment]
> But when the webassembly module has been loaded, the outline of the already opened file is not shown; I needed to add a new file and then tab back to get the outline.

I need more information about this. Did you wait until the WebAssembly module was fully loaded? Did you edit the file already? Did you switch to a different file while it was still loading? Does this issue only occur on the Safari / MacBook combination?

We need to distinguish between preparation time and the actual time that is needed in order to prepare and show the analyzes or outline. In the future, let us refer to the former as preparation time (the time where the "Loading WebAssembly..." is still there) and to the latter as run time (from the disappearance of "Loading WebAssembly" until the appearance of the outline).

> But in the first one it did not update unless traversing it the first time also needs very much time.

Do you refer here to the preparation time or the run time?

**Comment by vonwenckstern** [comment]
I did not edit the file in the mean-while.


Maybe you add two different notifications:
* `load webassembly parser (1/2)` (as you do int now, it is nice)
* `load outline builder (2/2)`
This has the advantage that the user sees that it changed and that it is ready soon

**Comment by 0xJMR** [comment]
I think the contents of this issue should be more or less satisfied. I will close it for now.
